//
// Created by Wihy on 1/4/26.
//

#ifndef ROYALEDELIVERYCLIENT_GLOBALS_H
#define ROYALEDELIVERYCLIENT_GLOBALS_H
#include <QString>

#define PI_ADDRESS "127.0.0.1" //FOR PROD USE 192.168.1.156

inline QString CLIENT_NAME;
inline QString RAW_PASSWORD;

#endif //ROYALEDELIVERYCLIENT_GLOBALS_H
